### ISSUE TITLE
Normal working, 2x not being accepted in applications

### ISSUE THREAD

**Issue by definitelynotrazu** [molarmanful/eldur#1]
Recently found this font, I'm a very big fan of it.
I tried to use the 0.0.3 2x size .bdf and .otb bitmap fonts, but they couldn't be opened in the KDE Plasma 5 font manager, nor could I get it to open in any of my other programs. The standard size variants are working fine though, only the 2x sized fail to load. (Edited since I didn't realize the standard size was working*)

Also another thing I noticed, is that eldur does not show up as a monospaced font while my other monospaced fonts do. I'm assuming this is some sort of metadata issue?

Thanks for your time.

**Comment by molarmanful** [comment]
Hi, thanks for raising this issue, sorry for the late reply. I don't currently have a Linux machine on hand, but my first guess would be something to do with bdfresize. I've caught a typo with the OTB resize part of the build script, but if the BDF doesn't work either then I'll have to investigate further. I assume the TTF works?

The monospace issue seems to be something related to [this](https://askubuntu.com/questions/1441908/monospace-font-is-not-recognized-as-a-monospace-font), so I'll also look into that.

**Comment by definitelynotrazu** [comment]
> I assume the TTF works?

Indeed the TTF is working flawlessly

> The monospace issue seems to be something related to [this](https://askubuntu.com/questions/1441908/monospace-font-is-not-recognized-as-a-monospace-font), so I'll also look into that.

I meant to write an update on this and completely forgot, my apologies. It turned out to be an issue of my fc-cache not having updated properly, after clearing it the TTF and normal bitmaps did show up as monospaced. 

> but if the BDF doesn't work either then I'll have to investigate further.

Aye I retested both to be sure, both 2x variants give the issue

**Comment by molarmanful** [comment]
Alright, after a bunch of messing around I found issues with the bdf resizing and other metadata that were messing up the fonts pretty badly. I've created a [pre-release here](https://github.com/molarmanful/eldur/releases/tag/v0.0.4-0) with 2x versions that hopefully work. Let me know, and I'll move towards a proper patch after. (Thanks in advance!)

**Comment by molarmanful** [comment]
Actually it seems like the above pre-release has an issue with the OTB width, so I have [another one](https://github.com/molarmanful/eldur/releases/tag/v0.0.4-1) that shouldn't have that issue.

**Comment by definitelynotrazu** [comment]
> Actually it seems like the above pre-release has an issue with the OTB width, so I have [another one](https://github.com/molarmanful/eldur/releases/tag/v0.0.4-1) that shouldn't have that issue.

Thanks for the fix, the 2x BDF is working great!
Something is bugged with the OTB however, it does load but it looks like this:
![image](https://github.com/molarmanful/eldur/assets/107396728/1328fb70-dcce-416a-ac7c-aa8424b07187)

**Comment by molarmanful** [comment]
Oh that is very strange... does the 1x OTB have this issue?
What program is that? I'll see if I can repro on my test env.

**Comment by definitelynotrazu** [comment]
> Oh that is very strange... does the 1x OTB have this issue? What program is that? I'll see if I can repro on my test env.

Tested the 1x OTB as well, same issue. The program in the picture is the KDE Plasma "font management" tab in settings, but it also shows up similarly in the terminal: 
![image](https://github.com/molarmanful/eldur/assets/107396728/1d8e9f01-dc85-4948-87e1-0140364c76f4)

**Comment by molarmanful** [comment]
Huh, so I've tried the OTB on Gnome Terminal, xterm, and Konsole. Gnome + xterm are fine, but Konsole doesn't like the font. I'm going to have to mess around with different OTB build methods and test more.

![image](https://github.com/molarmanful/eldur/assets/7122029/483f0324-0f70-443e-9a3e-9fba86d33f54)

**Comment by definitelynotrazu** [comment]
> Huh, so I've tried the OTB on Gnome Terminal, xterm, and Konsole. Gnome + xterm are fine, but Konsole doesn't like the font. I'm going to have to mess around with different OTB build methods and test more.
> 
> ![image](https://private-user-images.githubusercontent.com/7122029/306862133-483f0324-0f70-443e-9a3e-9fba86d33f54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NzYwNTUsIm5iZiI6MTcwODU3NTc1NSwicGF0aCI6Ii83MTIyMDI5LzMwNjg2MjEzMy00ODNmMDMyNC0wZjcwLTQ0M2UtOWEzZS05ZmJhODZkMzNmNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDQyMjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE0MzVhYjYzYjUzYmYwMzk5MDQ0M2U3OTVmZmUxMTBhNThkZjU0NTIwMGY4YWZhZjE0NDcwNjk5MzUwZjgxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.twBXdgW8jJ341L6vGkqvwQJBYjrPHmlmK5NDYlPZUxs)

Might just be a bug with Konsole since it renders on Gnome Term then, a lot of bugs in Qt5 KDE apps have been fixed with Qt6 variants, which will be released along with Plasma 6 (which comes out in just a few days actually)

Feel free to close the issue if you think it is in fact just an issue with Konsole, and thanks for updating the font I really enjoy it

**Comment by molarmanful** [comment]
No worries, I'll leave it open for now since I haven't ruled out the possibility of it being a bug on my end (e.g. [Cozette](https://github.com/slavfox/Cozette)'s OTB works fine).

Your support is much appreciated! I'll continue to see what I can do about the OTB, esp. since BDF/PCF/etc. are less supported nowadays.

**Comment by molarmanful** [comment]
[Newest prerelease](https://github.com/molarmanful/eldur/releases/tag/v0.0.4-2) seems to work on Konsole now!

**Comment by definitelynotrazu** [comment]
> [Newest prerelease](https://github.com/molarmanful/eldur/releases/tag/v0.0.4-2) seems to work on Konsole now!

Can confirm, 2x OTB is working great now!
