### ISSUE TITLE
Very wide spacing in Wezterm

### ISSUE THREAD

**Issue by definitelynotrazu** [molarmanful/eldur#2]
I'm not 100% sure if the problem lies with the font or Wezterm, but I did test a couple other bitmap fonts in Wezterm and they had no issues. I tested both the normal and 2x variants of the bdf and otb fonts. Result ends up looking like this: 
![image](https://github.com/molarmanful/eldur/assets/107396728/26f45182-ee7d-4b8b-a79a-ee7f22fe4a31)

**Comment by molarmanful** [comment]
Hmmm, I'm assuming this is with the latest version? I believe the TTF version should be fine (since that's what I use with Wezterm). Do previous versions have this kind of issue?

Thanks in advance.

EDIT: Oh also is this with the 2x version of the font?

**Comment by definitelynotrazu** [comment]
> Hmmm, I'm assuming this is with the latest version? I believe the TTF version should be fine (since that's what I use with Wezterm). Do previous versions have this kind of issue?
> 
> Thanks in advance.
> 
> EDIT: Oh also is this with the 2x version of the font?

Aye it's the latest version, and yes the TTF version is working in Wezterm, strictly occurs with the bitmap variants.

Previous versions (at least going back to 0.0.3) also have this issue.
Both the default size and 2x size of the bitmap fonts as well

**Comment by molarmanful** [comment]
Interesting... I'm unsure what's causing this, so I'll leave this issue open for now while I keep looking into this.

I suppose the temporary fix would be to use the TTF at the proper point size, but I realize this isn't an ideal solution. Apologies in advance.

**Comment by definitelynotrazu** [comment]
> Interesting... I'm unsure what's causing this, so I'll leave this issue open for now while I keep looking into this.
> 
> I suppose the temporary fix would be to use the TTF at the proper point size, but I realize this isn't an ideal solution. Apologies in advance.

No worries, Kitty is actually my main terminal, I just happened to notice it when I was messing with wezterm.
GL on figuring it out

**Comment by molarmanful** [comment]
Hi, very late but give [this release](https://github.com/molarmanful/eldur/releases/tag/v0.0.5) a try!

**Comment by definitelynotrazu** [comment]
All fixed!
